---
AllCops:
  TargetRubyVersion: 2.5
  
Metrics/BlockLength:
  Enabled: true
  Max: 100
  Exclude:
    - specs/**/*
    - Rakefile

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - specs/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - db/migrations/**/*
    - Rakefile

Style/MutableConstant:
  Exclude:
    - specs/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - specs/**/*

Style/MixinUsage:
  Exclude:
    - specs/**/*

Naming/MethodName:
  Exclude:
    - config/**/*

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100