---
AllCops:
  TargetRubyVersion: 2.5
  
Metrics/BlockLength:
  Enabled: true
  Max: 65
  Exclude:
    - spec/**/*
    - Rakefile

Security/YAMLLoad:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashSyntax:
  Enabled: true
  Exclude:
    - Rakefile

Style/SymbolArray:
  Enabled: true
  Exclude:
    - Rakefile